[features]
seeds = false
[programs.devnet]
passenger_assets= "HgmcLpipPCCTs9tXquEUAwws6ngonHp3b9aCahtauniq"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "/Users/gledsonjoaquimlopes/passenger_assets/node_modules/yarn/bin/yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
