[features]
seeds = false
[programs.localnet]
passenger_assets= "66yprobuiXwdor2ZT4gNEP6JjPqaK1AR1fdpWCYHYqNH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
